version: '3.8'
services:
  nginx:
    image: nginx:alpine
    ports:
      - 8001:80
    volumes:
      - .:/var/www
      - ./etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel

  laravel:
    build:
      context: .
    volumes:
      - ./:/var/www
    expose:
      - 9000
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - REDIS_PREFIX=reiz_laravel
      - CACHE_DRIVER=redis
    depends_on:
      - redis

  redis:
      image: redis
      command: redis-server --appendonly yes --appendfsync everysec
      ports:
        - 1001:6379
      volumes:
        - ./redis_data:/data


volumes:
  db_data: {}
